// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: feeds.sql

package database

import (
	"context"
	"database/sql"
)

const countFeeds = `-- name: CountFeeds :one
SELECT
  COUNT(*) AS count
FROM
  feeds
`

func (q *Queries) CountFeeds(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFeeds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds
WHERE id = ?1
`

func (q *Queries) DeleteFeed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, id)
	return err
}

const getFeed = `-- name: GetFeed :one
SELECT
  id, url, link, title,
(
    SELECT
      COUNT(*)
    FROM
      entries
    WHERE
      entries.feed_id = ?1) AS entryCount,
(
    SELECT
      count(*)
    FROM
      entries
    WHERE
      entries.feed_id = ?1
      AND entries.has_read = FALSE) AS unreadCount
FROM
  feeds
WHERE
  feeds.id = ?1
`

type GetFeedRow struct {
	ID          int64
	Url         sql.NullString
	Link        string
	Title       string
	Entrycount  int64
	Unreadcount int64
}

func (q *Queries) GetFeed(ctx context.Context, id int64) (GetFeedRow, error) {
	row := q.db.QueryRowContext(ctx, getFeed, id)
	var i GetFeedRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Link,
		&i.Title,
		&i.Entrycount,
		&i.Unreadcount,
	)
	return i, err
}

const listFeeds = `-- name: ListFeeds :many
SELECT
  id, url, link, title,
(
    SELECT
      count(*)
    FROM
      entries
    WHERE
      entries.feed_id = feeds.id
      AND entries.has_read = FALSE) AS unreadCount
FROM
  feeds
ORDER BY
  title ASC
LIMIT ?2 OFFSET ?1
`

type ListFeedsParams struct {
	Offset int64
	Limit  int64
}

type ListFeedsRow struct {
	ID          int64
	Url         sql.NullString
	Link        string
	Title       string
	Unreadcount int64
}

func (q *Queries) ListFeeds(ctx context.Context, arg ListFeedsParams) ([]ListFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedsRow
	for rows.Next() {
		var i ListFeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Link,
			&i.Title,
			&i.Unreadcount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeed = `-- name: UpsertFeed :one
INSERT INTO feeds(url, link, title)
  VALUES (?1, ?2, ?3)
ON CONFLICT (link)
  DO UPDATE SET
    url = excluded.url, title = excluded.title
  RETURNING
    id, url, link, title
`

type UpsertFeedParams struct {
	Url   sql.NullString
	Link  string
	Title string
}

func (q *Queries) UpsertFeed(ctx context.Context, arg UpsertFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, upsertFeed, arg.Url, arg.Link, arg.Title)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Link,
		&i.Title,
	)
	return i, err
}
