// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: feeds.sql

package database

import (
	"context"
	"database/sql"
)

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds
WHERE id = ?1
`

func (q *Queries) DeleteFeed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, id)
	return err
}

const getFeed = `-- name: GetFeed :one
SELECT
  id, url, link, title, collection_id,
(
    SELECT
      COUNT(*)
    FROM
      feed_entries fe
    WHERE
      fe.feed_id = ?1) AS entryCount,
(
    SELECT
      count(*)
    FROM
      feed_entries fe
    WHERE
      fe.feed_id = ?1
      AND fe.has_read = FALSE) AS unreadCount
FROM
  feeds
WHERE
  feeds.id = ?1
`

type GetFeedRow struct {
	ID           int64
	Url          sql.NullString
	Link         string
	Title        string
	CollectionID sql.NullInt64
	Entrycount   int64
	Unreadcount  int64
}

func (q *Queries) GetFeed(ctx context.Context, id int64) (GetFeedRow, error) {
	row := q.db.QueryRowContext(ctx, getFeed, id)
	var i GetFeedRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Link,
		&i.Title,
		&i.CollectionID,
		&i.Entrycount,
		&i.Unreadcount,
	)
	return i, err
}

const listFeeds = `-- name: ListFeeds :many
SELECT
  id, url, link, title, collection_id,
  count(*) OVER () AS total_count,
(
    SELECT
      count(*)
    FROM
      feed_entries fe
    WHERE
      fe.feed_id = feeds.id
      AND fe.has_read = FALSE) AS unreadCount
FROM
  feeds
WHERE
  CASE WHEN ?1 THEN
    CASE WHEN ?2 < 0 THEN
      collection_id IS NULL
    ELSE
      collection_id = ?2
    END
  ELSE
    TRUE
  END
ORDER BY
  title ASC
LIMIT ?4 OFFSET ?3
`

type ListFeedsParams struct {
	FilterByCollectionID interface{}
	CollectionID         interface{}
	Offset               int64
	Limit                int64
}

type ListFeedsRow struct {
	ID           int64
	Url          sql.NullString
	Link         string
	Title        string
	CollectionID sql.NullInt64
	TotalCount   int64
	Unreadcount  int64
}

func (q *Queries) ListFeeds(ctx context.Context, arg ListFeedsParams) ([]ListFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds,
		arg.FilterByCollectionID,
		arg.CollectionID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedsRow
	for rows.Next() {
		var i ListFeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Link,
			&i.Title,
			&i.CollectionID,
			&i.TotalCount,
			&i.Unreadcount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeed = `-- name: UpdateFeed :one
UPDATE
  feeds
SET
  collection_id = coalesce(?1, collection_id)
WHERE
  id = ?2
RETURNING
  id, url, link, title, collection_id
`

type UpdateFeedParams struct {
	CollectionID sql.NullInt64
	ID           int64
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, updateFeed, arg.CollectionID, arg.ID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Link,
		&i.Title,
		&i.CollectionID,
	)
	return i, err
}

const upsertFeed = `-- name: UpsertFeed :one
INSERT INTO feeds(url, link, title)
  VALUES (?1, ?2, ?3)
ON CONFLICT (link)
  DO UPDATE SET
    url = excluded.url, title = excluded.title
  RETURNING
    id, url, link, title, collection_id
`

type UpsertFeedParams struct {
	Url   sql.NullString
	Link  string
	Title string
}

func (q *Queries) UpsertFeed(ctx context.Context, arg UpsertFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, upsertFeed, arg.Url, arg.Link, arg.Title)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Link,
		&i.Title,
		&i.CollectionID,
	)
	return i, err
}
