// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Collection struct {
	ID    int32
	Title string
}

type Entry struct {
	ID           int32
	Link         string
	Title        string
	PublishedAt  pgtype.Timestamptz
	Author       pgtype.Text
	Content      pgtype.Text
	ThumbnailUrl pgtype.Text
}

type Feed struct {
	ID           int32
	Url          pgtype.Text
	Link         string
	Title        string
	CollectionID pgtype.Int4
}

type FeedEntry struct {
	FeedID  int32
	EntryID int32
	HasRead bool
}
