// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
)

type Entry struct {
	ID           int64
	Link         string
	Title        string
	PublishedAt  string
	Author       sql.NullString
	Content      sql.NullString
	ThumbnailUrl sql.NullString
	HasRead      int64
	FeedID       int64
}

type Feed struct {
	ID    int64
	Url   sql.NullString
	Link  string
	Title string
}
