// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
)

type Collection struct {
	ID       int64
	Title    string
	ParentID sql.NullInt64
}

type Entry struct {
	ID           int64
	Link         string
	Title        string
	PublishedAt  string
	Author       sql.NullString
	Content      sql.NullString
	ThumbnailUrl sql.NullString
}

type Feed struct {
	ID           int64
	Url          sql.NullString
	Link         string
	Title        string
	CollectionID sql.NullInt64
}

type FeedEntry struct {
	FeedID  int64
	EntryID int64
	HasRead int64
}
